[package]
name = "eepy-serial-host"
version = "0.1.0"
edition = "2024"
authors = ["arthomnix"]
license = "MIT"

[dependencies]
eepy-serial = { path = "../eepy-serial" }
serialport.workspace = true
postcard.workspace = true