[package]
name = "eepy-derive"
version = "0.1.0"
edition = "2024"
authors = ["arthomnix"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"