[package]
name = "eepytool"
version = "0.1.0"
edition = "2024"
authors = ["arthomnix"]
license = "MIT"

[dependencies]
eepy-serial-host = { path = "../eepy-serial-host" }
color-eyre = "0.6.3"
clap.workspace = true
tar.workspace = true
zstd.workspace = true