[package]
name = "eepytool"
version = "0.1.0"
edition = "2021"

[dependencies]
eepy-serial = { path = "../eepy-serial" }
postcard.workspace = true
clap.workspace = true
serialport.workspace = true
tar.workspace = true
zstd.workspace = true