[package]
name = "eepy-example-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eepy-sys = { path = "../eepy-sys" }
eepy-gui = { path = "../eepy-gui" }
embedded-graphics.workspace = true
heapless.workspace = true
panic-halt = "1.0"
